# Remove SSH_AUTH_SOCK to disable tmux automatically resetting the variable
set -sg escape-time 10

unbind C-b
set-option -g prefix C-o
bind-key C-o send-prefix


set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
#    Use a symlink to look up SSH authentication
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

set -g default-terminal "xterm-direct"
set -s extended-keys always
set -as terminal-features 'xterm*:extkeys'

